### PR TITLE
Update index.js to fix package individually.

### PR DESCRIPTION
**Pull request by slslazy**
The change allows the use of the package individually true combined with sls deploy function -f func_name.

### CODE REVIEW

**Comment by pgrzesik** [comment]
Hello, could you explain that solution a little bit? Would you be able to cover it with unit test? I'm not sure why/how that solves the problem and would really appreciate a walkthrough 🙇

**Comment by rileypriddle** [comment]
looks like its for this issue #605

**Comment by pgrzesik** [comment]
Thanks a lot for linking that @rileypriddle, it indeed seems like the solution to that issue. It would be good to confirm with test case that it solves the issue and we should be good to go with this one @slslazy 🚀

**Comment by rileypriddle** [comment]
Duplicate of #613

**Comment by pgrzesik** [comment]
Hello @slslazy 👋 Are you interested in getting this PR through the finish line? It would be good to confirm that it works as intended with a test case

**Comment by keyto123** [comment]
While you wait for this to merge.
`sed -i 's/inputOpt\.functionObj/this\.serverless\.service\.functions\[inputOpt\.function\]/' node_modules/serverless-python-requirements/index.js`

make this a bash function or set as a postinstall step in package.json to replace broken code with working one

**Comment by pgrzesik** [comment]
Thanks @slslazy 🙇  I will finalize it as a part of: https://github.com/serverless/serverless-python-requirements/pull/725 after stabilizing tests. I will close this PR.

**Pull request closed without merging**
