### PR TITLE
Exclude specified patterns from stripping

### PR DESCRIPTION
**Pull request by eoinsha**
- Allow specific packages to be excluded from stripping
- Add an option (`stripExcludes`), an array

### CODE REVIEW

**Comment by sergeyk** [comment]
This is a good PR, I was just about to make the same :)

The problem is that libraries like `tensorflow` need to be stripped, as they are too large to deploy even with the double-zipping trick, and stripping is safe to do. However, some libraries like `cv2` break on stripping (and don't even slim down that much anyway).

**Comment by IvanBernatovic** [comment]
Just came across an issue, one of the modules have issue when I use slim option so I was forced to avoid using slim and strip completely. Does this PR also enable exclusions for slim option or it's only for strip option?

**Comment by miketheman** [comment]
Can this branch be brought up to date and a test added?

**Comment by pgrzesik** [comment]
Hey @eoinsha - it's been a long time since this PR was proposed. I'm going to close it, if you feel like the issue is valid, please open a new issue or a new PR against the latest main branch. Thanks 🙇

**Pull request closed without merging**
