### PR TITLE
feat: Add architecture to requirements cache directory name

### PR DESCRIPTION
**Pull request by mLupine**
Now that Lambdas can be run on arm64 runtimes, Python dependencies with native bindings compiled on x86_64 hosts might not work on Graviton lambdas. This can generate quite a lot of issues with dependencies — for example when using LocalStack on x86_64 but deploying to arm64 runtimes.

This PR adds a suffix with architecture name to the cache directory path so that if dependencies are built for multiple architectures on a single computer, they won't be conflicting each other and there'll be no need to empty cache between those builds.

Side note: If #644 gets merged before this, `getRequirementsLayerPath` will also need to be [adjusted](https://github.com/mLupine/serverless-python-requirements/commit/fdcd0f0f791138f1264f1885bc1bb27f697b4e08).

### CODE REVIEW

**Comment by pgrzesik** [comment]
Hey @mLupine 👋 Thanks a lot for PR proposal - could you rebase it on top of the current master? Also I see that linting CI step is failing, could you look into that? Thanks in advance!  🙇

**Comment by mLupine** [comment]
Hi @pgrzesik, branch updated.

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Hey @mLupine - could you also please check formatting? It looks like it's failing :( The PR looks good in general though 👍 Let's clear that out and merge it

**Comment by mLupine** [comment]
That's weird, when I run `eslint .` or `npm run lint` locally, it doesn't find any formatting errors. I'll dig into it tomorrow.

**Comment by pgrzesik** [comment]
@mLupine From what I see it's `prettier` that is complaining, you might want to run `npm run prettify`

**Comment by mLupine** [comment]
@pgrzesik Indeed, missed that. Should be fine now :)

**Comment by mLupine** [comment]
@pgrzesik Well, the check failed again. Seems that `npm run prettify` for some reason skips files within the `lib/` directory. I ran `prettier` manually, now it should _really_ be fine 😉

**Review by pgrzesik — APPROVED** [review]
Thanks @mLupine 🙇 As for `prettier`, I'll look into that, thanks!

**Pull request merged**
