### PR TITLE
refactor: Replace `lodash.set` with `set-value`

### PR DESCRIPTION
**Pull request by mhassan1**
Resolves https://github.com/serverless/serverless-python-requirements/issues/675

### CODE REVIEW

**Review by pgrzesik — COMMENTED** [review]
Thanks for the proposal @mhassan1  - Looks like we have some failing tests at the moment - could you look into that?

**Comment by mhassan1** [comment]
@pgrzesik I'm not sure how the change in this PR could be causing those failures. What do you think?

**Comment by pgrzesik** [comment]
You're totally right, I didn't check the errors previously - it seems like there's some issue with one of the GH actions - I'm looking into it

**Comment by pgrzesik** [comment]
Hello @mhassan1 - I believe I've fixed the CI issue, could you please rebase your branch against current `master`?

**Review by pgrzesik — APPROVED** [review]
Thank you @mhassan1 🙇

**Pull request merged**
