### PR TITLE
Translate Pipfiles to Requirements in modules

### LINKED ISSUE #268: Package individually not working with pipenv modules
I have a service where each function is a module using pipenv to manage dependencies for each module. The plugin doesn't generate requirements.txt using pipenv unless I have a Pipfile in the root of the service, even if I have them in the modules. However, when I do that, the plugin generates a requirements.txt for each module using the root pipfile instead of the pipfile in the module itself.

I think the issue might be in the function "pipfileToRequirements()" in pipenv.js. It always passes the service root to the spawnSync call.

Packaging seems to work if I manually generate the requirements.txt in each module prior to sls deploy/package. Though there is still another issue where serverless generates two zips per function. One zip is named the lambda function name specified in serverless.yml that follows include/exclude but otherwise would contain the entire service. The other is a zip named the lambda function after it is deployed which I believe is the one generated by this plugin. My understanding according to the docs is there should only be 2 zips?

I'm not sure if these two issues are related to each other nor if the second issue isn't really an issue and is just how it works currently, so I'd like some insight into this if possible.

I've created a reproduction repo for this here:
[https://github.com/username-dot-com/sls-python-test](https://github.com/username-dot-com/sls-python-test)

### PR DESCRIPTION
**Pull request by leaveningagent**
The plugin does not properly handle Pipfiles that sit in submodules
since the pipenv integration does not anticipate submodules.

This commit reworks the pipenv integration such that submodules are
supported. This changes will convert Pipfiles into requirements as
they are parsed by `pip.js` instead of doing it as a pre-processing
step. This is done since the submodule discovery logic sits in pip.js.

This closes #268.

### CODE REVIEW

**Comment by leaveningagent** [comment]
I'll try to get the tests passing soon, that seems like a minor change.

**Comment by leaveningagent** [comment]
I've no clue why the tests cannot find `pipenv`, any idea?

**Comment by jack1902** [comment]
Is this fix still being implemented as I have this exact issue. Much prefer pipenv over requirements.txt files but this is forcing my hand to use requirements.txt without this fix getting implemented

**Comment by ComfyDust** [comment]
Running into this issue as well. =[

**Comment by endre-synnes** [comment]
Any news about this issue? Would be nice to have this functionality merged 😄

**Comment by michael-c-hoffman** [comment]
will this ever be merged?

**Comment by pgrzesik** [comment]
Hey @leaveningagent  - it's been a long time since this PR was proposed. I'm going to close it, if you feel like the issue is valid, please open a new issue or a new PR against the latest main branch. Thanks 🙇

**Pull request closed without merging**
